import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Sidebar from './components/Sidebar';
import FollowBar from "./components/FollowBar";
import Modal from "./components/Modal";
import LoginModal from "./components/modals/LoginModal";
import RegisterModal from "./components/modals/RegisterModal";
import { getServerSession } from "next-auth";
import { AuthProvider } from "./providers/AuthProvider";

export const metadata: Metadata = {
  title: "Twitter Clone",
  description: "Generated by create my app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Fetch the session on the server
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className="antialiased">
        <div className="h-screen bg-black">
          <div className="container h-full mx-auto xl:px-30 max-w-6xl">
            <div className="grid grid-cols-4 h-full">
              {/* Wrap in AuthProvider */}
              <AuthProvider session={session}>
                <Toaster />
                <Sidebar />
                <LoginModal />
                <RegisterModal />
                <div
                  className="
                    col-span-3
                    lg:col-span-2
                    border-x-[1px]
                    border-neutral-800
                  "
                >
                  {children}
                </div>
                <FollowBar />
              </AuthProvider>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
